// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Structure } from "./Structure";

export type ComparisonLogicalStructure = { ref_structure: Structure | null, comp_structure: Structure | null, structure_differences: Array<boolean>, substructure_differences: Array<ComparisonLogicalStructure>, };
