// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhysicalStructure } from "./PhysicalStructure";

export type ComparisonPhysicalStructure = { ref_structure: PhysicalStructure, comp_structure: PhysicalStructure, difference_indices: Array<[number, number]>, };
