// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * storing the physical bytes of a certain section of the document
 */
export type PhysicalStructure = { stream_name: string, structure_name: string | null, bytes: string, start_index: bigint, end_index: bigint, description: string | null, };
