// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructureItem } from "./StructureItem";

/**
 * A Struct that is used for storing the information of a structure
 * within a document
 */
export type Structure = { name: string, structure: Array<StructureItem>, substructs: Array<Structure>, };
