// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Struct that is used for storing the information of a field within a structure
 */
export type StructureItem = { name: string, value: string, description: string | null, };
